### ISSUE TITLE
linux installation: instructions not clear

### ISSUE THREAD

**Issue by Exalaber** [milochristiansen/rubble8#2]
I downloaded the rubble 8 from the following link: 'https://github.com/milochristiansen/rubble8/releases'
which I got from the bay 12 forums. I downloaded the 'rubble.8.5.4.7z' file, and attempted to install rubble in a brand new installation of dwarf fortress version 44_04 for linux. I started by reading the readme for rubble 8 which lead me to extract the archive to 'df/rubble' then I could not find a 'df/rubble/other' so I created one and placed the 'linux and OSX installer.tar' in that folder. I then extracted the second archive and it contained a shell script with the same name. When I ran the script I received the following errors:

$ ./InstallRubble.sh                                                                                                                                                               
cp: cannot stat './linux/rubble': No such file or directory                                                                                                                                    
rm: cannot remove './../rubble.exe': No such file or directory                                                                                                                                 
chmod: cannot access './../rubble': No such file or directory                                                                                                                                  
chmod: cannot access './webUI/browser': No such file or directory  

Upon inspection of the script it seems to expect the folder df/rubble/other/linux' which should contain a binary name rubble. I can only assume that this is meant to be contained in the 'linux and OSX installer.tar' however, I have been unable to find it, or any directory named linux in the whole rubble tree. The script also seems to imply the existence of a windows binary named rubble.exe in df/rubble which I have also been unable to find.

All in all I am very confused.

**Comment by milochristiansen** [comment]
That directory you got `linux and OSX installer.tar` from? Yeah, it has lots of important stuff Rubble needs. *That* directory is `df/rubble/other`. I just checked the .7z package, and it is properly packed, are you sure you unpacked it correctly? You should have ended up with `rubble.exe`, `other/`, and `addons/` in your `<df>/rubble/` directory. Also, the installer shell script is supposed to be unpacked and run right where it is.

Note that the repository has a different structure than the .7z file. That is intended.

**Comment by Exalaber** [comment]
Having re-downloaded the archive, it seems to work. I believe that I accidentally downloaded the source files. I am sorry to have posted here. (I swear I thought I had checked that)

**Comment by milochristiansen** [comment]
Well, it would be a pretty easy mistake to make, just one tiny miss-click...

Good luck, and hopefully all else goes smoothly! If not, you know where to go (and who to bug :) )
