### ISSUE TITLE
Invalid Dwarf Fortress version

### ISSUE THREAD

**Issue by Rdna123** [milochristiansen/rubble8#4]
I am not able to find a 0.44.7 version of dwarf  fortress, but there is a 0.44.07. Or am I missing something

**Comment by milochristiansen** [comment]
I am 99% sure Rubble ignores leading zeros in version numbers. Are you actually having an issue, and if so where is your log file?

**Comment by Rdna123** [comment]
I had deleted the the files, I will redo it to send the log later.

**Comment by Rdna123** [comment]
It affects nothing it just I thought the version was wrong because there is
no 0.44.7 available at least

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by milochristiansen** [comment]
Rubble parses the DF version so that it can reason about how versions relate to each other. This parsing strips any unnecessary leading zeros.

Numerically `07 == 7 == 00007`.
